<div class="mt-5 d-flex justify-content-center align-items-center">
    <div class="card w-50">
        <div class="card-header">
            Ingreso
        </div>
        <div class="card-body">
                <form action="Autenticar" method="post">
                <div class="mb-3">
                    <label class="form-label">Usuario</label>
                    <input type="text" class="form-control" name="user">

                </div>
                <div class="mb-3">
                    <label class="form-label">Contraseña</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                </div>
                </form>
        </div>
    </div>
</div>