<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Agregar nuevo producto
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <form class="was-validated" method="post" action="agregar">
            <div class="mb-3">
                <label for="prod" class="form-label">Nombre del producto</label>
                <input type="text" class="form-control form-control-sm form-control" id="prod" name="pNombre" required>
                <div class="valid-feedback">Nombre valido</div>
                <div class="invalid-feedback">Por favor ingrese un nombre valido</div>
            </div>
            <div class="mb-3">
                <label for="precio" class="form-label">Precio</label>
                <input type="number" step="0.01" class="form-control form-control-sm" id="precio" name="pPrecio" required>
                <div class="valid-feedback">Precio valido</div>
                <div class="invalid-feedback">Por favor ingrese un precio valido</div>
            </div>
            <div class="mb-3">
                <label for="desc" class="form-label">Descripción</label>
                <input type="text" class="form-control form-control-sm" id="desc" name="pDesc" required>
                <div class="valid-feedback">Descripción valida</div>
                <div class="invalid-feedback">Por favor ingrese una descripción valida</div>
            </div>
            <div class="mb-3">
                <label for="selector" class="form-label">Proveedor</label>
                <select class="form-select" id="selector" name="proveedor">
                    <?php foreach($proveedores as $proveedor){ ?>
                        <option value="<?php echo $proveedor->id_provn ?>"><?php echo $proveedor->nombre ?></option>
                    <?php } ?>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Agregar nuevo proveedor
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <form class="was-validated" method="post" action="agregarProv">
              <div class="mb-3">
                  <label for="prov" class="form-label">Nombre del proveedor</label>
                  <input type="text" class="form-control form-control-sm form-control" id="prov" name="provNombre" required>
                  <div class="valid-feedback">Nombre valido</div>
                  <div class="invalid-feedback">Por favor ingrese un nombre valido</div>
              </div>
              <div class="mb-3">
                  <label for="email" class="form-label">Mail del proveedor</label>
                  <input type="email"  class="form-control form-control-sm" id="mail" name="eMail" required>
                  <div class="valid-feedback">Mail valido</div>
                  <div class="invalid-feedback">Por favor ingrese un mail valido</div>
              </div>
              <div class="mb-3">
                  <label for="tel" class="form-label">Teléfono del proveedor</label>
                  <input type="tel"  class="form-control form-control-sm" id="tel" name="tel" pattern="[0-9]{8,15}"  required>
                  <div class="valid-feedback">Teléfono valido</div>
                  <div class="invalid-feedback">Por favor ingrese un teléfono valido</div>
              </div>
              <div class="mb-3">
                  <label for="precio" class="form-label">Descripción</label>
                  <input type="text" class="form-control form-control-sm" id="precio" name="provDesc" required>
                  <div class="valid-feedback">Descripción valida</div>
                  <div class="invalid-feedback">Por favor ingrese una descripción valida</div>
              </div>
              <button type="submit" class="btn btn-primary">Agregar</button>
          </form>
      </div>
    </div>
  </div>
</div>